### PR TITLE
fix: bridge command

### LINKED ISSUE #1175: Does not start on macOS
Neovide does not start on macOS after updating to (today's commit ```dd74ff```). The window pops up and closes almost immediately, logs shows ERROR Neovide requires nvim version 0.4 or higher while I have 0.6.1

Old version works (from a week ago)

**To Reproduce**
Start nevoid from command line or application

 - OS: macOS 12.1
 - Neovide Version 0.8.0
 - NVIM v0.6.1
 
**LOG**
TRACE [neovide] Neovide version: 0.8.0
DEBUG [neovide::settings::window_geometry] Loaded window settings: Windowed { position: PhysicalPosition { x: 1280, y: 1080 }, size: Dimensions { width: 106, height: 41 } }
TRACE [neovide::renderer::fonts::caching_shaper] Using font_size: 28.00px
TRACE [neovide::renderer::fonts::font_loader] Loading font FontKey { bold: false, italic: false, family_name: None }
TRACE [neovide::renderer::fonts::caching_shaper] Font width: 17.23px 17.36px
TRACE [neovide::renderer::fonts::caching_shaper] Fudge factor: 0.99
TRACE [neovide::renderer::fonts::caching_shaper] Fudged font size: 27.63px
TRACE [neovide::renderer::fonts::caching_shaper] Fudged font width: 17.00px
TRACE [neovide::renderer::fonts::font_loader] Loading font FontKey { bold: false, italic: false, family_name: None }
INFO [neovide::window] window created (scale_factor: 2.0000, font_dimensions: Dimensions { width: 17, height: 35 })
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::renderer::fonts::caching_shaper] Shaping text:
INFO [neovide::bridge::command] Starting neovim with: Command { std: "/bin/zsh" "-lc" "\x1b]1337;RemoteHost=ommited@ommited\x07\x1b]1337;CurrentDir=/Users/ommited\x07\x1b]1337;ShellIntegrationVersion=12;shell=zsh\x07/usr/local/bin/nvim --embed", kill_on_drop: false }
ERROR [neovide::bridge] Neovide requires nvim version 0.4 or higher. Download the latest version here https://github.com/neovim/neovim/wiki/Installing-Neovim

### PR DESCRIPTION
**Pull request by jaeheonji**
This PR resolves #1175 

## What kind of change does this PR introduce?
- Fix

## Did this PR introduce a breaking change? 
- No

First of all, I got rid of Interactive (`-i`) options in shell. because, If a banner or similar text is output at the start of the shell, the output buffer of the executed command cannot be retrieved normally.

**Example:**
화면 캡처 2022-02-16 015645

(But, in the case of Windows, the command is executed through `wsl`. It may not be affected by files such as `bashrc`, `zshrc`, `bashenv`, `zshenv`, etc)

And referring to the specification of the `Command` as follows

> * No arguments to the program
> * Inherit the current process’s environment

In macOS, It seems that we do not need to run the command through the shell (with `-c`), but simply execute the run command directly.

This may not be a perfect solution. So, I'd really appreciate it if you could give me feedback.

### CODE REVIEW

File: src/bridge/command.rs [hunk 1]
```diff
@@ -48,26 +48,26 @@ fn build_nvim_cmd() -> TokioCommand {
 }
 
 // Creates a shell command if needed on this platform (wsl or macos)
-fn create_platform_shell_command(command: String) -> Option<StdCommand> {
+fn create_platform_shell_command(command: &str, args: Vec<&str>) -> Option<StdCommand> {
```
Comment (MultisampledNight) [inline src/bridge/command.rs:51]: Nit: If you change the signature here already, I think it's just fine to take a slice here (`&[&str]`), too.

File: src/bridge/command.rs [hunk 2]
```diff
@@ -80,7 +80,8 @@ fn platform_exists(bin: &str) -> bool {
 }
 
 fn platform_which(bin: &str) -> Option<String> {
-    if let Some(mut which_command) = create_platform_shell_command(format!("which {}", bin)) {
+    if let Some(mut which_command) = create_platform_shell_command("which", vec![bin]) {
+        info!("Running which command: {:?}", which_command);
```
Comment (MultisampledNight) [inline src/bridge/command.rs:84]: Nit: A `info!` might be a bit too loud than actually needed. I think a `debug!` or even `trace!` might be better, the actual command executed is rarely needed imo.

File: src/bridge/command.rs [hunk 3]
```diff
@@ -48,26 +48,26 @@ fn build_nvim_cmd() -> TokioCommand {
...
+
         Some(result)
     } else {
         None
     }
 }
 
 fn platform_exists(bin: &str) -> bool {
-    if let Some(mut exists_command) = create_platform_shell_command(format!("exists -x {}", bin)) {
+    // if let Some(mut exists_command) = create_platform_shell_command(format!("exists -x {}", bin)) {
```
Comment (MultisampledNight) [inline src/bridge/command.rs:69]: Even smaller nit: Delete the line rather than commenting it out. Git takes care of old things already, you don't need to preserve them manually.

**Review by MultisampledNight — COMMENTED** [review]
Some small nits, but looks good to me generally.

File: src/bridge/command.rs (hunk 3 above)
Comment (jaeheonji) [reply src/bridge/command.rs]: Oh! This is my mistake. I forgot to delete 😅  thank you!

**Comment by bmulholland** [comment]
I confirm this works for me on my 2021 Macbook Pro w. M1 Pro

**Comment by MultisampledNight** [comment]
To be honest, then I think nothing keeps this from merging anymore.

**Comment by shaunsingh** [comment]
LGTM and runs fine on my machine

**Comment by j4qfrost** [comment]
Absolutely not a complaint, but this also includes refactor changes in addition to the fix. Thanks for PR. Merging.

**Comment by clason** [comment]
> I confirm this works for me on my 2021 Macbook Pro w. M1 Pro

Did you test the bundle as well (`cargo bundle --release`), or just the standard binary?

**Comment by j4qfrost** [comment]
> > I confirm this works for me on my 2021 Macbook Pro w. M1 Pro
> 
> Did you test the bundle as well (`cargo bundle --release`), or just the standard binary?

Did a problem arise?

**Comment by clason** [comment]
Yes, I can't launch the app from the Finder anymore. (`open neovide.app` still works, though, which implies that there's a problem with the environment passed to Neovide.)

**Comment by jaeheonji** [comment]
@clason Have you ever installed `neovim` through `brew` package manager?

**Comment by clason** [comment]
No.

**Comment by clason** [comment]
I think this assumption is not valid when running from Finder:

> In macOS, It seems that we do not need to run the command through the shell (with -c), but simply execute the run command directly.

(I'm sorry for not testing this before it got merged.)

**Comment by jaeheonji** [comment]
I just assumed it was a problem because neovim installed with brew did not exist in the PATH.
Anyway, I'm not sure what exactly is the problem currently, so I'll try to re-test it.

**Comment by clason** [comment]
The problem is that if you launch an app from Finder and not through a shell, it will not have most of the environment variables set that are necessary for it to find and start Neovim.

**Comment by clason** [comment]
No, that's definitely not it. It's a proper regression.

**Comment by jaeheonji** [comment]
When running an app through Finder, a specific command can be normally executed only when the shell is executed in `Interactive Mode` like `/bin/zsh -i "which nvim"`

However, the problem is that if a specific command is executed interactively, incorrect output is obtained according to the settings of each shell. For example, in the case of zsh, when executing the `neofetch` command or `echo "..."` in the `.zshrc` file.

If we roll back to the previous code, execution through Finder works normally., but the user should never put any code that causes stdout or a command like `echo` in `.zshrc` or `.bashrc`.

I still don't know what is the best way to solve all of this.

**Comment by jaeheonji** [comment]
Okay.. First of all, you need `lc`options to run it in Finder.

However, in this case, if the user installed neovim via `brew`, it will not run because the installation path of `nvim` is not in the `PATH`. So at this point it seems like the best way to specify this like:

```
$ sudo ln -s /opt/homebrew/Celler/neovim/.../bin/nvim /usr/local/bin/nvim
```

**Comment by clason** [comment]
I think that is discouraged by homebrew...

(Personally, I install Neovim by hand, so this won't affect me, but forcing people to do that will lead to a lot of complaints from homebrew users....)

**Comment by jaeheonji** [comment]
```
...
    } else if cfg!(target_os = "macos") {
        let shell = env::var("SHELL").unwrap_or_else(|_| "/bin/sh".to_string());
        let mut result = StdCommand::new(&shell);
        result.env("PATH", "/opt/homebrew/bin");

        result.args(&["-lc"]);
        result.arg(format!("{} {}", command, args.join(" ")));

        Some(result)
}
```
