### PR TITLE
fix: --wsl error if using non-POSIX shell as login shell

### LINKED ISSUE #2941: "--wsl" option can fail if the WSL login shell is not POSIX compliant
**Describe the bug**
`--wsl` option can fail if the WSL login shell is not POSIX compliant. This occurs when setting `elvish` as the login shell, since it does not support the syntax `$SHELL`.

**To Reproduce**
1. Use `chsh` to set login shell as `elvish` within WSL
2. Launch `neovide --wsl`

**Expected behavior**
Neovide launches successfully

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Neovide Version 0.14.0
 - Neovim Version N/A

**Additional context**
I'd be happy to make a PR, changing `$SHELL` to `/bin/sh` is the simplest solution, since it guarantees a POSIX shell.  I'd have to check the code if there are any config options that might make this a breaking change. If so we could add a config option that allows specification of which shell to run.

### PR DESCRIPTION
**Pull request by ejrichards**
Reopening #2949 , realized you need to specify `--shell-type login` to wsl.exe to not be a breaking change and accidentally closed the previous PR.

## What kind of change does this PR introduce?
- Fixes #2941 

## Did this PR introduce a breaking change? 
- No
- `nvim_cmd_impl` changed to use the syntax `wsl --shell-type login -- <bin> <args>` rather than `wsl $SHELL -lc <bin> <args>` which will still spawn the default shell.  The previous implementation actually spawns two shells.
- `create_platform_shell_command` changed to use `/bin/sh`, since non-POSIX shells might not have the `which` command

@fredizzimo 

> Thanks, but we can't change the shell to `sh`, becuase the user might have only configured their default shell and not `sh`. So, custom paths for example won't be set, which means that things like LSP won't work.
> 
> So, we need to find another way to do this, maybe bootstrap through another shell, like was done on macOS #2928.

It is only using `/bin/sh` for doing `which nvim` and `nvim -v`, the `wsl -- <bin>` syntax does spawn the user's default shell, for example, if I run `wsl -- sudo ps -ef` I can see:

```
236     233  0 00:08 pts/0    00:00:00 /usr/local/bin/elvish -c sudo ps -ef
```

When my default shell is `elvish`

### CODE REVIEW

**Comment by fredizzimo** [comment]
Yes, this looks much better, the `--shell-type` parameter didn't exist when the login shell launch was initially implemented here https://github.com/neovide/neovide/pull/1118. So, that's why the previous workaround had to be used.

> It is only using /bin/sh for doing which nvim and nvim -v, the wsl -- <bin> syntax does spawn the user's default shell, for example, if I run wsl -- sudo ps -ef I can see:

Can we change that to use the login shell as well? We want the path to be set, for example if `nvim` has been installed to `~/.local/bin` and added to the path by the user.

**Comment by ejrichards** [comment]
Part of the issue originally was that `elvish` doesn't have the `which` command.

I'll double check tomorrow if the config parameter that sets the nvim path works through WSL to skip the `which` call. Then the concession can be on the smaller group of people like me that decide to use a more obscure shell.

Will update tomorrow.

**Comment by ejrichards** [comment]
Updated to use `wsl --shell-type login -- <bin> <args>` in all cases

**Review by fredizzimo — APPROVED** [review]
Thanks, this looks good now, but someone else need to test before we merge.

File: src/bridge/command.rs [hunk 1]
```diff
@@ -183,7 +185,7 @@ fn neovim_ok(bin: &str, args: &[String]) -> Result<bool> {
     if unexpected_output {
         let error_message = create_error_message(bin, &stdout, non_matching_stderr_lines, is_wsl);
         let command = if is_wsl {
-            "wsl '$SHELL' -lc '{bin} -v'"
+            "wsl --shell-type login -- {bin} -v"
```
Comment (fredizzimo) [inline src/bridge/command.rs:188]: This fails in the CI on the nightly clippy check 
https://github.com/neovide/neovide/actions/runs/12694686463/job/35407023838?pr=2950#step:6:456

```
error: this looks like a formatting argument but it is not part of a formatting macro
   --> src\bridge\command.rs:188:40
    |
188 |             "wsl --shell-type login -- {bin} -v"
    |                                        ^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#literal_string_with_formatting_args
    = note: `-D clippy::literal-string-with-formatting-args` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::literal_string_with_formatting_args)]`

error: this looks like a formatting argument but it is not part of a formatting macro
   --> src\bridge\command.rs:190:26
    |
190 |             "$SHELL -lc '{bin} -v'"
    |                          ^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#literal_string_with_formatting_args
```

It's not really your fault, it has been broken before too, but I have only seen the linter complain now.  I think this pr https://github.com/neovide/neovide/pull/2405 broke it. It doesn't really work as expected either, so it would ne good if it could be fixed. But it can be done separately by someone else too.

The message is supposed to show which command to run when there's a problem. Previously it showed `Check that your shell doesn't output anything extra when running` followed by the command, and now just `Please check your shell configuration` followed by the wrongly formatted command.

Comment (fredizzimo) [reply src/bridge/command.rs:188]: Sorry for adding more to this, that's not your fault, but I'm on vaccation and can't do any fixing myself. This check is also wrong
```rust
    let unexpected_output = !output.status.success()
        || !stdout.starts_with("NVIM v")
        || non_matching_stderr_lines.len() != stderr.lines().count();
```
It should be 
```rust
    let unexpected_output = !output.status.success()
        || !stdout.starts_with("NVIM v")
        || non_matching_stderr_lines.len()
```
So that it fails on any stderr output excpect the ignored "screen size is bogus" lines. But the output still prints the full stderr.

Comment (ejrichards) [reply src/bridge/command.rs:188]: Could switch to something like `<bin>` in the meantime?

Comment (fredizzimo) [reply src/bridge/command.rs:188]: You can use `format!("wsl --shell-type login -- {bin} -v")`

Comment (fredizzimo) [reply src/bridge/command.rs:188]: Actually, leave this check for now at least, I don't understand how it even works currently, but somehow it seems to do the job, so better not touch it, unless you can figure it out.

```rust
    let unexpected_output = !output.status.success()
        || !stdout.starts_with("NVIM v")
        || non_matching_stderr_lines.len() != stderr.lines().count();
```

Comment (ejrichards) [reply src/bridge/command.rs:188]: Just tested it, looks like it is doing the opposite of what it should be doing based on #2374, will add a fix shortly.

**Comment by ejrichards** [comment]
Tested with: `let stderr = "your 1x123123 screen size is bogus. expect trouble";`
Launches successfully

Tested with: `let stderr = "your 1x123123 screen size is bogus. expect trouble\nasdf";`
```
ERROR: Unexpected output from neovim binary:
        /usr/bin/nvim -v
stdout: NVIM v0.10.3
Build type: RelWithDebInfo
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info

stderr: asdf


Please check your WSL configuration.
wsl --shell-type login -- /usr/bin/nvim -v
```

**Comment by fredizzimo** [comment]
Can you check the final case as well, `let stderr = "some error";? I don't see any problems, but it's worth checking.

And the output could be
```
Please check your WSL configuration. Only the output from "nvim -v" should be output when you run:
wsl --shell-type login -- /usr/bin/nvim -v
```

**Comment by ejrichards** [comment]
Sure, looks good, using `let stderr = "some error";`:

```
ERROR: Unexpected output from neovim binary:
        /usr/bin/nvim -v
stdout: NVIM v0.10.3
Build type: RelWithDebInfo
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info

stderr: some error


Please check your WSL configuration.
wsl --shell-type login -- /usr/bin/nvim -v
```

**Comment by fredizzimo** [comment]
Thank you!
